### ISSUE TITLE
Issue running bhbot on Linux

### ISSUE THREAD

**Issue by mlehmann76** [ilpersi/BHBot#137]
I've tried running bhbot under linux and was successfull, but it brings up an error message. bhbot is still accepting commands but doesn't work.

operating system: Linux 5.3.11-1-default #1 SMP Tue Nov 12 18:57:39 UTC 2019 (0a195a8) x86_64 x86_64 x86_64 GNU/Linux

chromium Version 78.0.3904.108 (openSUSE Build) (64-Bit)

tested with:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (IcedTea 3.14.0) (build 1.8.0_232-b08 suse-1.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

and 

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-suse-lp151.1.56-x8664)
OpenJDK 64-Bit Server VM (build 10.0.2+13-suse-lp151.1.56-x8664, mixed mode)

20:23:45,595 INFO - BHBot v43 build on Tue Nov 26 19:54:04 CET 2019 started.
20:23:45,598 INFO - GIT commit id: b6d9a70f1f5d3ebf58a9f1ffec857bc1f095879e  time: 2019-11-23T22:45:30+0100
20:23:46,548 INFO - Settings loaded from file
20:23:47,103 INFO - Bot started successfully!
Starting ChromeDriver 2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634) on port 8670
Only local connections are allowed.
20:24:23,256 INFO - Game element found. Starting to run bot..
Exception in thread "MainThread" java.lang.NoClassDefFoundError: javafx/beans/property/IntegerProperty
        at MainThread.run(MainThread.java:926)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.IntegerProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more
hide
20:27:01,468 INFO - User command: <hide>
20:27:01,578 INFO - Chrome window has been hidden.

**Comment by mlehmann76** [comment]
after install javafx it doesn't show the error message anymore, but doesn't start the raid after "do raid", it just was doing nothing.

[settings.zip](https://github.com/ilpersi/BHBot/files/3898664/settings.zip)

**Comment by ilpersi** [comment]
I am able to reproduce this and as stated in #134 Linux is not supported ATM.

I am going to rename this issue and make it as an enhacement.

**Comment by MugenEnzan** [comment]
I guess this is probably on hold until the Unity version is available, right?

**Comment by ilpersi** [comment]
@MugenEnzan 
Honestly, I don't know if I'll ever be able to support Linux. It is more a matter of time/priorities than Flash vs Unix. In the end nowadays you can get Windows VPS for cheap.

I can say that I improved compatibility with the latest versions of Chrome and that should help with Linux but I don't have a Linux box anymore to test with so if you have time you can try to give it a shot and I can help with the setup (there some undocumented options that can help you).

**Comment by MugenEnzan** [comment]
Yea I get you. I am currently running it in VM for compatibility.

Just thought I would ask :)

Thanks!
