### ISSUE TITLE
Random crash on "Not enough token popup detected!"

### ISSUE THREAD

**Issue by dotdeas** [ilpersi/BHBot#144]
I'm getting random crashes and restarts when there is not enough tokens.

```
08:56:48,178 READOUT - Tokens: 13, required: >1, Gauntlet cost: 5
08:56:51,081 INFO - Attempting gauntlet at level 635...
08:56:58,450 WARN - Not enough token popup detected! Closing trial window.
08:57:07,175 ERROR - Unmanaged exception in main run loop
 java.lang.NullPointerException: null
        at BrowserManager.clickOnSeg(BrowserManager.java:792) ~[BHBot.jar:?]
        at DungeonThread.run(DungeonThread.java:742) [BHBot.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
08:57:07,225 WARN - Doing driver emergency restart...
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 33806
Only local connections are allowed.
[1579593436.637][WARNING]: Timed out connecting to Chrome, retrying...
[1579593447.866][WARNING]: Timed out connecting to Chrome, retrying...
08:57:31,651 INFO - Game element found. Starting to run bot..
08:57:54,364 INFO - Gear check dismissed.
08:57:55,852 INFO - Initializing autoShrine to make sure it is disabled
```

Using the build from issue #142 that fixes the expedition issue.

```
09:05:25,031 INFO - User command: <print version>
09:05:25,033 INFO - BHBot v43 build on Mon Jan 20 20:29:28 CET 2020 started.
09:05:25,065 INFO - GIT commit id: 67437ab35dab9be74025a3a442788a3c6d60638f  time: 2020-01-11T13:38:18+0100
```

Running on Windows 10

**Comment by dotdeas** [comment]
After some more checking it seems like the readout of avaible tokes, tickets, badges and so are wrong. It says 13 but there are only 1.

**Comment by Fortigate** [comment]
There is a bug with the new guild perks that causes a visual error of full resources when that's not the case, do you know if this is the case here? If so we just need to have a look at the 'Not enough Tokens' message closing.

**Comment by ilpersi** [comment]
Attached to the crash log there also is an image of the screen, can you please attach it to the issue? Just make sure to hide sensitive information.

**Comment by ilpersi** [comment]
@dotdeas no feedback in 9 days so I am closing this. If you still have issues fell free to re-open
