### ISSUE TITLE
the bot does not change mystical runes correctly

### ISSUE THREAD

**Issue by fabioganga1** [ilpersi/BHBot#181]
**Describe the bug**
the bot does not change mystical runes correctly

**The logs:**
2020-10-17 08:00:19,539 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - BHBot v46.3 build on Mon Oct 05 21:51:06 BST 2020 started.
2020-10-17 08:00:19,553 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - GIT commit id: e614d54f3ea7521899dd7ce71677e0b51ea8ba05  time: 2020-10-05T21:47:11+0200
2020-10-17 08:00:20,879 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - Settings loaded from file
2020-10-17 08:00:20,906 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - Character: qwerty
2020-10-17 08:00:20,910 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - Created screenshot folder in C:\Users\fabio\OneDrive\BHBot-master\screenshots
2020-10-17 08:00:21,452 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Bot started successfully!
2020-10-17 08:00:48,098 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Game element found. Starting to run bot..
2020-10-17 08:01:51,921 [BlockerThread] INFO com.github.ilpersi.BHBot.BHBotLogger - News popup dismissed.
2020-10-17 08:01:54,497 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Initializing autoShrine to make sure it is disabled
2020-10-17 08:02:01,631 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Startup check to determined configured minor runes
2020-10-17 08:02:10,344 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Created screenshot sub-folder C:\Users\fabio\OneDrive\BHBot-master\screenshots\errors
2020-10-17 08:02:16,513 [DungeonThread] WARN com.github.ilpersi.BHBot.BHBotLogger - Error: Unable to detect right minor rune!
2020-10-17 08:02:16,514 [DungeonThread] ERROR com.github.ilpersi.BHBot.BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2020-10-17 08:02:16,516 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Legendary Experience equipped in left slot.
2020-10-17 08:02:16,517 [DungeonThread] ERROR com.github.ilpersi.BHBot.BHBotLogger - Unmanaged exception in main run loop
java.lang.NullPointerException: null
	at com.github.ilpersi.BHBot.AutoRuneManager.initialize(AutoRuneManager.java:142) ~[BHBot.jar:?]
	at com.github.ilpersi.BHBot.DungeonThread.run(DungeonThread.java:372) [BHBot.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-17 08:02:16,535 [DungeonThread] WARN com.github.ilpersi.BHBot.BHBotLogger - Doing driver emergency restart...
2020-10-17 08:02:43,107 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Game element found. Starting to run bot..

**Screenshots**
![wrong-rune-detection_20201017](https://user-images.githubusercontent.com/39866048/96331400-c1397e80-1054-11eb-8eb9-b76b35aec598.png)

**Settings**
[settings.zip](https://github.com/ilpersi/BHBot/files/5395162/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (x64)]
 - Browser [Chromium]
 - Version [BHBot v46.3 build on Mon Oct 05 21:51:06 BST 2020 started.)

**Comment by ilpersi** [comment]
The mythic experience cue is probably unreliable.
I will try to fix this, please consider mythic rune support experimental for the moment.

**Comment by ilpersi** [comment]
@fabioganga1 
Can you please trigger the issue one more time? When the bot is not able to recognize the runes it is contributing them anonymously and I had an error in my back-end logic and I was not getting contributions.

Thank you.

**Comment by ilpersi** [comment]
@fabioganga1 
Not sure if it was you and I got some rune contribution.

Can you please try with [this updated build](https://drive.google.com/u/0/uc?id=1Vtv2DZ44lxslnzEPoT_-dit_8MlW9jUV&export=download) if the error is still there?

**Comment by fabioganga1** [comment]
hasn't changed anything

**Comment by ilpersi** [comment]
@fabioganga1 
New build [here](https://drive.google.com/u/0/uc?id=1Vtv2DZ44lxslnzEPoT_-dit_8MlW9jUV&export=download): can you please try again?

You have to download the file and use it to replace the same file in you BHBot folder.

**Comment by fabioganga1** [comment]
hasn't changed anything

**Comment by ilpersi** [comment]
@fabioganga1 
What mythic rune are you having issues with? From your screenshot I am assuming it is the minor experience one: is this correct?

**Comment by fabioganga1** [comment]
[these I did.zip](https://github.com/ilpersi/BHBot/files/5441524/these.I.did.zip)

**Comment by ilpersi** [comment]
You are not using the version I provided you in this thread.

> 2020-10-26 20:51:21,949 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - BHBot v46.3 **build on Mon Oct 05** 21:51:06 BST 2020 started.
> 2020-10-26 20:51:21,954 [main] INFO com.github.ilpersi.BHBot.BHBotLogger - GIT commit id: e614d54f3ea7521899dd7ce71677e0b51ea8ba05  time: 2020-10-05T21:47:11+0200

Please make sure to replace BHBot.jar with the one I provided as part of this thread

**Comment by fabioganga1** [comment]
it's working

**Comment by ilpersi** [comment]
The new [v46.4](https://github.com/ilpersi/BHBot/releases/tag/v46.4) is including all these modifications. Thanks for your contribution.

The only mythic rune that can still cause issues is the gold finding one. I did not get enough contributions to make it reliable. I'll wait for more to come and release a further update. 👍🏻 

I am closing this one. Feel free to open a new one.
